;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; svemit-c.scm -- BDD-to-C emitter
;;
;; Generates C evaluation functions from BDD synthesis results.
;; Each combinational output becomes a C function using temp vars
;; decomposed from the BDD structure (Shannon expansion).
;;
;; BDD variable names are "signal_N" (bit N of signal).
;; Uses bdd-id for O(1) hash-based memoization.
;;
;; Requires svbase.scm, svbv.scm, and hashtable module.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(require-modules "hashtable")

(define *cemit-cache* #f)
(define *cemit-lines* '())
(define *cemit-counter* 0)

(define (cemit-reset!)
  (set! *cemit-cache* (make-hash-table 4999 (lambda (x) (if (number? x) x 0))))
  (set! *cemit-lines* '())
  (set! *cemit-counter* 0))

(define (cemit-lookup bdd)
  (let ((result (*cemit-cache* 'retrieve (bdd-hash bdd))))
    (if (eq? result '*hash-table-search-failed*) #f result)))

(define (cemit-store! bdd name)
  (*cemit-cache* 'add-entry! (bdd-hash bdd) name))

(define (cemit-line! s)
  (set! *cemit-lines* (cons s *cemit-lines*)))

;; Convert BDD variable name to C identifier: "signal[N]" -> "signal_N"
(define (bdd-name->c-name name)
  (let* ((chars (string->list name))
         (out (let loop ((cs chars) (acc '()))
                (cond ((null? cs) (reverse acc))
                      ((char=? (car cs) #\[) (loop (cdr cs) (cons #\_ acc)))
                      ((char=? (car cs) #\]) (loop (cdr cs) acc))
                      (else (loop (cdr cs) (cons (car cs) acc)))))))
    (list->string out)))

;; Map a BDD to a C temp var name, emitting assignment lines
(define (bdd->c bdd)
  (cond
    ((bdd-true? bdd) "1")
    ((bdd-false? bdd) "0")
    (else
      (let ((cached (cemit-lookup bdd)))
        (if cached cached
            (let* ((var (bdd-node-var bdd))
                   (var-name (bdd-name->c-name (bdd-name var)))
                   (hi (bdd-high bdd))
                   (lo (bdd-low bdd))
                   (hi-c (bdd->c hi))
                   (lo-c (bdd->c lo))
                   (tname (string-append "_t"
                            (number->string *cemit-counter*))))
              (set! *cemit-counter* (+ *cemit-counter* 1))
              (cemit-store! bdd tname)
              (cemit-line! (string-append "    uint8_t " tname " = "
                            var-name " ? " hi-c " : " lo-c ";"))
              tname))))))

;; Emit C header with eval functions to a port (file).
;; inputs: ((input name) ...) from collect-port-signals
;; assigns: ((sig . bdd-list) ...) from bv-synth-combinational
(define (emit-c-eval-to-port mod-name inputs assigns port)
  (define nl (list->string (list (integer->char 10))))
  (define (out s) (display s port) (display nl port))

  (out "/*")
  (out (string-append " * " mod-name "_eval.h -- Generated combinational evaluation functions"))
  (out " * Auto-generated by svemit-c.scm from BDD synthesis")
  (out " */")
  (out "")
  (out "#include <stdint.h>")
  (out "")

  ;; One function per output
  (for-each
    (lambda (asgn)
      (let* ((sig (car asgn))
             (bv (cdr asgn))
             (w (length bv))
             (rtype (cond ((> w 16) "uint32_t")
                          ((> w 8) "uint16_t")
                          (else "uint8_t")))
             (fname (string-append "eval_" (symbol->string sig))))

        (cemit-reset!)

        ;; Generate C expressions for all bits (populates *cemit-lines*)
        (define bit-exprs '())
        (for-each
          (lambda (bdd)
            (set! bit-exprs (cons (bdd->c bdd) bit-exprs)))
          bv)
        (set! bit-exprs (reverse bit-exprs))

        (displayln "  " fname ": " (number->string *cemit-counter*) " temp vars")

        ;; Function signature
        (out (string-append "static inline " rtype " " fname "("))
        (let loop ((ins inputs) (first #t))
          (if (not (null? ins))
              (let* ((inp (car ins))
                     (name (symbol->string (cadr inp)))
                     (iw (width-get (cadr inp)))
                     (itype (cond ((> iw 16) "uint32_t")
                                  ((> iw 8) "uint16_t")
                                  (else "uint8_t"))))
                (if (not first) (out ","))
                (out (string-append "    " itype " " name))
                (loop (cdr ins) #f))))
        (out ") {")

        ;; Extract individual bits from packed inputs
        (for-each
          (lambda (inp)
            (let* ((name (symbol->string (cadr inp)))
                   (iw (width-get (cadr inp))))
              (let loop ((i 0))
                (if (< i iw)
                    (begin
                      (out (string-append "    uint8_t " name "_"
                            (number->string i) " = (" name " >> "
                            (number->string i) ") & 1;"))
                      (loop (+ i 1)))))))
          inputs)

        ;; Temp variable computations (reverse to get correct order)
        (for-each out (reverse *cemit-lines*))

        ;; Compose result from bits
        (out (string-append "    " rtype " _r = 0;"))
        (let loop ((i 0) (bits bit-exprs))
          (if (< i w)
              (begin
                (out (string-append "    _r |= ((" rtype ")"
                      (car bits) " & 1) << " (number->string i) ";"))
                (loop (+ i 1) (cdr bits)))))
        (out "    return _r;")
        (out "}")
        (out "")))
    assigns))
