;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; svgates.scm -- Gate library and BDD-to-netlist technology mapper
;;
;; Author : Claude / Mika Nystroem
;; Date   : March 2026
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; This file provides:
;;
;;   1. A standard cell library (INV, NAND2, NOR2, AND2, OR2, XOR2,
;;      MUX2, BUF, TIEH, TIEL)
;;   2. Flip-flop cells (DFF, DFFR, DFFS, DFFRS)
;;   3. BDD-to-gate decomposition (technology mapping)
;;   4. Structural Verilog netlist emission
;;
;; Requires svbase.scm and the svsynth interpreter (bdd-* primitives).
;;
;; Usage:
;;   > (load "sv/src/svbase.scm")
;;   > (load "sv/src/svgates.scm")
;;   > (define a (bdd-var "a"))
;;   > (define b (bdd-var "b"))
;;   > (gate-emit-netlist "test" (list (cons "y" (bdd-and a b)))
;;                               (list "a" "b") (list "y"))
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 1. GATE LIBRARY DEFINITION
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Each gate is a list: (name (port-list) area)
;; Ports are: (name direction) where direction is in/out

(define *gate-lib*
  '((INV    ((A in) (Y out))       1)
    (BUF    ((A in) (Y out))       1)
    (NAND2  ((A in) (B in) (Y out))  2)
    (NOR2   ((A in) (B in) (Y out))  2)
    (AND2   ((A in) (B in) (Y out))  2)
    (OR2    ((A in) (B in) (Y out))  2)
    (XOR2   ((A in) (B in) (Y out))  3)
    (XNOR2  ((A in) (B in) (Y out))  3)
    (MUX2   ((A in) (B in) (S in) (Y out))  4)
    (TIEH   ((Y out))  0)
    (TIEL   ((Y out))  0)
    (DFF    ((D in) (CK in) (Q out))  6)
    (DFFR   ((D in) (CK in) (RN in) (Q out))  7)
    (DFFS   ((D in) (CK in) (SN in) (Q out))  7)
    (DFFRS  ((D in) (CK in) (RN in) (SN in) (Q out))  8)))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 2. GATE LIBRARY VERILOG DEFINITIONS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; (gate-lib-verilog) -- emit Verilog module definitions for all
;; cells in the gate library.  These are behavioral models suitable
;; for simulation.
(define (gate-lib-verilog)
  (define lines '())
  (define (emit . args) (set! lines (cons args lines)))

  (emit "// Standard cell library -- behavioral models")
  (emit "// Generated by svgates.scm")
  (emit "")

  ;; INV
  (emit "module INV (input A, output Y);")
  (emit "  assign Y = ~A;")
  (emit "endmodule")
  (emit "")

  ;; BUF
  (emit "module BUF (input A, output Y);")
  (emit "  assign Y = A;")
  (emit "endmodule")
  (emit "")

  ;; NAND2
  (emit "module NAND2 (input A, B, output Y);")
  (emit "  assign Y = ~(A & B);")
  (emit "endmodule")
  (emit "")

  ;; NOR2
  (emit "module NOR2 (input A, B, output Y);")
  (emit "  assign Y = ~(A | B);")
  (emit "endmodule")
  (emit "")

  ;; AND2
  (emit "module AND2 (input A, B, output Y);")
  (emit "  assign Y = A & B;")
  (emit "endmodule")
  (emit "")

  ;; OR2
  (emit "module OR2 (input A, B, output Y);")
  (emit "  assign Y = A | B;")
  (emit "endmodule")
  (emit "")

  ;; XOR2
  (emit "module XOR2 (input A, B, output Y);")
  (emit "  assign Y = A ^ B;")
  (emit "endmodule")
  (emit "")

  ;; XNOR2
  (emit "module XNOR2 (input A, B, output Y);")
  (emit "  assign Y = ~(A ^ B);")
  (emit "endmodule")
  (emit "")

  ;; MUX2: Y = S ? B : A
  (emit "module MUX2 (input A, B, S, output Y);")
  (emit "  assign Y = S ? B : A;")
  (emit "endmodule")
  (emit "")

  ;; TIEH (constant 1)
  (emit "module TIEH (output Y);")
  (emit "  assign Y = 1'b1;")
  (emit "endmodule")
  (emit "")

  ;; TIEL (constant 0)
  (emit "module TIEL (output Y);")
  (emit "  assign Y = 1'b0;")
  (emit "endmodule")
  (emit "")

  ;; DFF: basic D flip-flop
  (emit "module DFF (input D, CK, output reg Q);")
  (emit "  always @(posedge CK) Q <= D;")
  (emit "endmodule")
  (emit "")

  ;; DFFR: D flip-flop with active-low async reset
  (emit "module DFFR (input D, CK, RN, output reg Q);")
  (emit "  always @(posedge CK or negedge RN)")
  (emit "    if (!RN) Q <= 1'b0;")
  (emit "    else     Q <= D;")
  (emit "endmodule")
  (emit "")

  ;; DFFS: D flip-flop with active-low async set
  (emit "module DFFS (input D, CK, SN, output reg Q);")
  (emit "  always @(posedge CK or negedge SN)")
  (emit "    if (!SN) Q <= 1'b1;")
  (emit "    else     Q <= D;")
  (emit "endmodule")
  (emit "")

  ;; DFFRS: D flip-flop with active-low async reset and set
  (emit "module DFFRS (input D, CK, RN, SN, output reg Q);")
  (emit "  always @(posedge CK or negedge RN or negedge SN)")
  (emit "    if (!RN)      Q <= 1'b0;")
  (emit "    else if (!SN) Q <= 1'b1;")
  (emit "    else           Q <= D;")
  (emit "endmodule")
  (emit "")

  ;; Return as a single string
  (apply string-append
         (map (lambda (l) (string-append (apply string-append l) *nl*))
              (reverse lines))))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 3. BDD-TO-GATE TECHNOLOGY MAPPING
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Wire name counter for internal nets
(define *wire-cnt* 0)
(define (new-wire)
  (set! *wire-cnt* (+ *wire-cnt* 1))
  (string-append "n" (number->string *wire-cnt*)))

;; Instance counter
(define *inst-cnt* 0)
(define (new-inst prefix)
  (set! *inst-cnt* (+ *inst-cnt* 1))
  (string-append prefix (number->string *inst-cnt*)))

;; Netlist accumulator: list of (cell-type inst-name ((port . wire) ...))
(define *netlist* '())
(define (add-gate cell inst connections)
  (set! *netlist* (cons (list cell inst connections) *netlist*)))

;; Cache: maps BDD nodes to wire names, avoids duplicating logic.
;; Uses bdd-equal? for lookup since bdd-id only returns the root
;; variable id, which is not unique per BDD node.
(define *bdd-wire-cache* '())

(define (cache-lookup bdd)
  (let loop ((entries *bdd-wire-cache*))
    (cond
      ((null? entries) #f)
      ((bdd-equal? (caar entries) bdd) (cdar entries))
      (else (loop (cdr entries))))))

(define (cache-store bdd wire)
  (set! *bdd-wire-cache*
        (cons (cons bdd wire) *bdd-wire-cache*)))

;; (map-bdd-to-gates bdd) -- decompose a BDD into gate instances.
;; Returns the wire name carrying the result.
;;
;; Strategy: Shannon expansion with pattern matching.
;; At each BDD node:  f = ITE(var, high, low)
;;   = MUX2(A=low, B=high, S=var)
;;
;; Special cases recognized:
;;   TRUE  => TIEH
;;   FALSE => TIEL
;;   var   => var (direct wire)
;;   NOT var => INV
;;   a AND b => AND2
;;   a OR b  => OR2
;;   a XOR b => XOR2 (detected via pattern)
;;   NOT(a AND b) => NAND2
;;   NOT(a OR b) => NOR2
(define (map-bdd-to-gates bdd)
  ;; Check cache first
  (let ((cached (cache-lookup bdd)))
    (if cached cached
        (let ((wire (map-bdd-to-gates-inner bdd)))
          (cache-store bdd wire)
          wire))))

(define (map-bdd-to-gates-inner bdd)
  (cond
    ;; Constant TRUE
    ((bdd-true? bdd)
     (let ((w (new-wire)))
       (add-gate "TIEH" (new-inst "u_tieh") (list (cons "Y" w)))
       w))

    ;; Constant FALSE
    ((bdd-false? bdd)
     (let ((w (new-wire)))
       (add-gate "TIEL" (new-inst "u_tiel") (list (cons "Y" w)))
       w))

    ;; Pure variable: ITE(v, TRUE, FALSE) = v
    ((and (bdd-true? (bdd-high bdd)) (bdd-false? (bdd-low bdd)))
     (bdd-name (bdd-node-var bdd)))

    ;; NOT variable: ITE(v, FALSE, TRUE) = !v
    ((and (bdd-false? (bdd-high bdd)) (bdd-true? (bdd-low bdd)))
     (let ((w (new-wire))
           (var-name (bdd-name (bdd-node-var bdd))))
       (add-gate "INV" (new-inst "u_inv")
                 (list (cons "A" var-name) (cons "Y" w)))
       w))

    ;; Try to recognize 2-input gate patterns, then fall back to MUX
    (else (map-bdd-optimized bdd))))

;; (map-bdd-optimized bdd) -- try to match 2-input gate patterns
;; before falling back to MUX decomposition.
(define (map-bdd-optimized bdd)
  (let ((var (bdd-node-var bdd))
        (hi  (bdd-high bdd))
        (lo  (bdd-low bdd)))
    (cond
      ;; AND: ITE(a, b, FALSE) = a AND b  (where b is a variable)
      ((bdd-false? lo)
       (let ((w (new-wire))
             (a-wire (bdd-name var))
             (b-wire (map-bdd-to-gates hi)))
         (add-gate "AND2" (new-inst "u_and")
                   (list (cons "A" a-wire) (cons "B" b-wire) (cons "Y" w)))
         w))

      ;; OR: ITE(a, TRUE, b) = a OR b
      ((bdd-true? hi)
       (let ((w (new-wire))
             (a-wire (bdd-name var))
             (b-wire (map-bdd-to-gates lo)))
         (add-gate "OR2" (new-inst "u_or")
                   (list (cons "A" a-wire) (cons "B" b-wire) (cons "Y" w)))
         w))

      ;; NAND: ITE(a, NOT b, TRUE) -- check if hi = NOT(something) and lo = TRUE
      ;; Actually: NAND(a,b) = ITE(a, NOT b, TRUE)
      ((and (bdd-true? lo)
            (not (bdd-const? hi))
            (bdd-false? (bdd-high hi))
            (bdd-true? (bdd-low hi)))
       ;; hi is NOT(b)
       (let ((w (new-wire))
             (a-wire (bdd-name var))
             (b-wire (bdd-name (bdd-node-var hi))))
         (add-gate "NAND2" (new-inst "u_nand")
                   (list (cons "A" a-wire) (cons "B" b-wire) (cons "Y" w)))
         w))

      ;; NOR: ITE(a, FALSE, NOT b) -- NOR(a,b) = ITE(a, FALSE, NOT b)
      ((and (bdd-false? hi)
            (not (bdd-const? lo))
            (bdd-false? (bdd-high lo))
            (bdd-true? (bdd-low lo)))
       ;; lo is NOT(b)
       (let ((w (new-wire))
             (a-wire (bdd-name var))
             (b-wire (bdd-name (bdd-node-var lo))))
         (add-gate "NOR2" (new-inst "u_nor")
                   (list (cons "A" a-wire) (cons "B" b-wire) (cons "Y" w)))
         w))

      ;; XOR: ITE(a, NOT b, b) -- XOR(a,b) = ITE(a, NOT b, b)
      ((and (not (bdd-const? hi))
            (not (bdd-const? lo))
            (bdd-equal? hi (bdd-not lo))
            (bdd-false? (bdd-high hi))
            (bdd-true? (bdd-low hi)))
       (let ((w (new-wire))
             (a-wire (bdd-name var))
             (b-wire (bdd-name (bdd-node-var lo))))
         (add-gate "XOR2" (new-inst "u_xor")
                   (list (cons "A" a-wire) (cons "B" b-wire) (cons "Y" w)))
         w))

      ;; XNOR: ITE(a, b, NOT b) -- XNOR(a,b) = ITE(a, b, NOT b)
      ((and (not (bdd-const? hi))
            (not (bdd-const? lo))
            (bdd-equal? lo (bdd-not hi))
            (bdd-false? (bdd-high lo))
            (bdd-true? (bdd-low lo)))
       (let ((w (new-wire))
             (a-wire (bdd-name var))
             (b-wire (bdd-name (bdd-node-var hi))))
         (add-gate "XNOR2" (new-inst "u_xnor")
                   (list (cons "A" a-wire) (cons "B" b-wire) (cons "Y" w)))
         w))

      ;; General: MUX2(A=low, B=high, S=var)
      (else (map-bdd-general bdd)))))

;; (map-bdd-general bdd) -- fall back to MUX2 decomposition.
(define (map-bdd-general bdd)
  (let ((w (new-wire))
        (var-wire (bdd-name (bdd-node-var bdd)))
        (hi-wire (map-bdd-to-gates (bdd-high bdd)))
        (lo-wire (map-bdd-to-gates (bdd-low bdd))))
    (add-gate "MUX2" (new-inst "u_mux")
              (list (cons "A" lo-wire)
                    (cons "B" hi-wire)
                    (cons "S" var-wire)
                    (cons "Y" w)))
    w))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 4. NETLIST EMISSION
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; (gate-reset!) -- reset all synthesis state
(define (gate-reset!)
  (set! *wire-cnt* 0)
  (set! *inst-cnt* 0)
  (set! *netlist* '())
  (set! *bdd-wire-cache* '()))

;; (gate-emit-netlist mod-name assigns inputs outputs)
;; Emit a structural Verilog netlist.
;;   assigns: list of (output-name . bdd)
;;   inputs: list of input signal name strings
;;   outputs: list of output signal name strings
(define (gate-emit-netlist mod-name assigns inputs outputs)
  (gate-reset!)

  ;; Map each BDD to gates
  (define output-wires
    (map (lambda (a)
           (cons (car a) (map-bdd-to-gates (cdr a))))
         assigns))

  ;; Collect all internal wire names
  (define internal-wires '())
  (for-each
    (lambda (gate)
      (for-each
        (lambda (conn)
          (let ((wire (cdr conn)))
            (if (and (not (member wire inputs))
                     (not (member wire outputs))
                     (not (member wire internal-wires)))
                (set! internal-wires (cons wire internal-wires)))))
        (caddr gate)))
    *netlist*)

  ;; Emit module header
  (displayln "module " mod-name " (")
  (for-each (lambda (i) (displayln "  input " i ",")) inputs)
  (let ((outs outputs))
    (let loop ((rest outs))
      (if (not (null? rest))
          (begin
            (display "  output ")
            (display (car rest))
            (if (null? (cdr rest)) (newline) (displayln ","))
            (loop (cdr rest))))))
  (displayln ");")
  (newline)

  ;; Emit wire declarations for internal nets
  (if (not (null? internal-wires))
      (begin
        (display "  wire ")
        (display (sv-join ", " (reverse internal-wires)))
        (displayln ";")
        (newline)))

  ;; Emit gate instances
  (for-each
    (lambda (gate)
      (let ((cell (car gate))
            (inst (cadr gate))
            (conns (caddr gate)))
        (display "  ")
        (display cell)
        (display " ")
        (display inst)
        (display " (")
        (display (sv-join ", "
                  (map (lambda (c)
                         (string-append "." (car c) "(" (cdr c) ")"))
                       conns)))
        (displayln ");")))
    (reverse *netlist*))

  ;; Connect output wires
  (newline)
  (for-each
    (lambda (ow)
      (let ((out-name (car ow))
            (wire (cdr ow)))
        (if (not (equal? out-name wire))
            (displayln "  assign " out-name " = " wire ";"))))
    output-wires)

  (newline)
  (displayln "endmodule")

  ;; Report statistics
  (displayln "")
  (displayln "// Statistics:")
  (displayln "//   Gates: " (number->string (length *netlist*)))
  (displayln "//   Wires: " (number->string (length internal-wires))))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 5. FULL SYNTHESIS FROM AST
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; (synth-to-gates mod) -- full synthesis pipeline:
;; parse AST -> BDDs -> gate netlist -> Verilog
(define (synth-to-gates mod)
  (bdd-env-reset!)
  (gate-reset!)

  (define name (module-name mod))
  (define ports (collect-port-signals (module-ports mod)))
  (define body (module-body-items mod))
  (define outputs (sv-filter (lambda (p) (eq? 'output (car p))) ports))
  (define inputs (sv-filter (lambda (p) (eq? 'input (car p))) ports))

  (define in-names (map (lambda (p) (symbol->string (cadr p))) inputs))
  (define out-names (map (lambda (p) (symbol->string (cadr p))) outputs))

  ;; Create BDD variables for inputs
  (for-each (lambda (p) (bdd-lookup (cadr p))) inputs)

  ;; Build BDDs for combinational logic
  (define bdd-assigns (synth-combinational body))

  ;; Convert to (name-string . bdd) pairs
  (define assigns
    (map (lambda (a) (cons (symbol->string (car a)) (cdr a)))
         bdd-assigns))

  ;; Emit gate library header
  (displayln "// Synthesized gate-level netlist for " (symbol->string name))
  (displayln "// Generated by svgates.scm")
  (newline)

  ;; Emit structural netlist
  (gate-emit-netlist
    (string-append (symbol->string name) "_gates")
    assigns in-names out-names))
