// Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
// SPDX-License-Identifier: Apache-2.0

**PROLOG**

 // AUTOMATICALLY GENERATED DO NOT EDIT                          
 // GENERATED BY genpg                                           
                                                                 
`include "hlp_checkers_ext.vs"                                 
                                                                 
**EARLY**
                                                                 
module hlp_sai_security_addr_pg                                  
 #(                                                              
  DEFAULT_PG = 0                                                 
  )                                                              
  (                                                              
  input  logic                                   clk,            
  input  logic                                   rst_n,          
                                                                 
  input  logic [hlp_pkg::W_MGMT_ADDR-1:0]        i_addr,         
  input  logic                                   i_v,            

  **BASESTRAP**
                                                                 
  // Management  connections                                     
  output hlp_imn_pkg::pg_bit_t                   o_pg            
);                                                               
                                                                 
  // lintra -50503 "Naming - use of double underscore"         
                                                                 
  //import packages                                              
  import hlp_pkg::*;                                             
  import hlp_register_constants_pkg::*;                          
  import hlp_c_imn_pkg::*;                                       
  import hlp_imn_pkg::*;                                         
                                                                 
  hlp_imn_pkg::pg_bit_t                   pg;                    
                                                                 
**DECLS**

**CODE**

**EPILOG**

  always_ff @(posedge clk or negedge rst_n) begin                
    if      (~rst_n)                                             
      o_pg <= DEFAULT_PG;                                        
    else if (i_v)                                                
      o_pg <= pg;                                                
  end // always_ff begin                                         
  // lintra +50503 "Naming - use of double underscore"         
endmodule                                                        
