% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("set")
import ("parseparams")
import ("mscheme")
import ("xmlparse")

import ("csv")

table ("RangeRef", "Range", "Refany")
sorted_table ("RangeRef", "Range", "Refany")
table ("TextRangeTbl", "Text", "SortedRangeRefTbl")

table ("RangeText", "Range", "Text")
sorted_table ("RangeText", "Range", "Text")

interface ("SBAddress")

module ("Range")
list ("Range", "Range")
table ("TextRangeList", "Text", "RangeList")

resource ("pg_template.sv.tmpl")
resource ("hlp_pg_template.sv.tmpl")
bundle ("PgToolSVTemplates")

module ("PgCRIF")
interface ("PgField")

implementation ("Main")

program ("genpg")
