// Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
// SPDX-License-Identifier: Apache-2.0

**PROLOG**

 // AUTOMATICALLY GENERATED DO NOT EDIT                          
 // GENERATED BY genpg                                           
 
**EARLY**
                                                                 
module 
**MODULE_NAME**
 #( 
  DEFAULT_PG = 0
  )
  (                                                              
  input  logic [**ADDR_BITS**-1:0]               i_addr,
  input  logic                                   i_v,

  **BASESTRAP**

  // Management  connections
  output logic [$clog2(**NUM_PG**)-1:0]    o_pg
);                                                               
                                                                 
  logic [$clog2(**NUM_PG**)-1:0] pg;

  // lintra -50503 "Naming - use of double underscore"
**DECLS**

**CODE**

**EPILOG**

  assign o_pg = pg;

  // lintra +50503 "Naming - use of double underscore"
endmodule
