% Copyright (c) 2026 Intel Corporation.  All rights reserved.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("globelib")

Module ("Airport")
Table  ("TextAirport", "Text", "Airport")

library ("airports")
