% Copyright (c) 2026 Intel Corporation.  All rights reserved.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("json")
import ("globelib")

Module ("GeoFeature")
Module ("GeoJSON")
Module ("GeoJSONWriter")
Module ("SvgWriter")

library ("geodata")
