# Multiresolution contour plot
# Generated by plydemo

set terminal pdfcairo size 12,16 font ',10'
set output '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_2/face_contours.pdf'

set multiplot layout 4,1

set view map
set contour base
unset surface
set cntrparam levels auto 20
set xrange [-2.1136728620451586e6:1.8221766475085083e6]
set yrange [-2.1746126842756164e6:1.6327365914497306e6]
unset key
unset clabel
set format z ''

set title 'Level 0 (sigma=32)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_2/face_level0.dat' with lines lc 'black'

set title 'Level 1 (sigma=7.9)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_2/face_level1.dat' with lines lc 'black'

set title 'Level 2 (sigma=2)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_2/face_level2.dat' with lines lc 'black'

set title 'Level 3 (raw)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_2/face_level3.dat' with lines lc 'black'

unset multiplot
