#!/bin/sh -x
# Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
# SPDX-License-Identifier: Apache-2.0

# Use GNU sed if available (needed for \U uppercase on macOS)
if command -v gsed >/dev/null 2>&1; then
  SED=gsed
else
  SED=sed
fi

DERIV=../$(../../../m3arch.sh)

#rm -rf ${DERIV}
mkdir ${DERIV} || echo

#rm -f rdl.y.*
#rm -f rdlParseExt.e
#rm -f rdl.l
#rm -f rdl.t


mv_if_different()
{
    cand=$1
    targ=$2

    ls -l $targ
    
    if [ ! -f "${targ}" ]; then
        echo "${targ} does not exist"
        mv ${cand} ${targ}
    else
        if [ `cmp ${cand} ${targ}` ]; then
            echo "${targ} is different from ${cand}, copying"
            mv ${cand} ${targ}
        else
            echo "${targ} same as ${cand}, removing ${cand}"
            rm ${cand}
        fi
    fi
}

make_interface()
{
    fn=$1
    nm=$2
    ifn_t=${DERIV}/${nm}.i3
    ifn=${ifn_t}.tmp
    
    cat > ${ifn} <<EOF
INTERFACE ${nm};

(* automatically generated by $0 *)

TYPE T = {
EOF
    cat ${fn} | awk 'BEGIN {comma=""} {printf("%s %s ", comma, $1); comma=","}' >> ${ifn}
    
    cat >> ${ifn} <<EOF
};

CONST Names = ARRAY T OF TEXT {
EOF

        cat ${fn} | awk 'BEGIN {comma=""} {printf("%s \"%s\" ", comma, $1); comma=","}' >> ${ifn}


    cat >> ${ifn} <<EOF  
};

CONST Brand = "${nm}";

END ${nm}.
EOF
    mv_if_different ${ifn} ${ifn_t}
}

camelize()
{
    in=$1;
    echo $in | $SED 's/\.dat$//' | $SED  -e 's/_\(.\)/\U\1/g' -e 's/^\(.\)/Rdl\U\1/'
}

mk_e_fragment()
{
    fn=$1
    base=$2
    nm=$3
    echo mk_e_fragment $fn $base $nm
    efn_tgt=${DERIV}/${base}.e.fragment
    efn=${efn_tgt}.tmp
    cat  > ${efn} <<EOF

${base}: { val: ${nm}.T }
EOF
    cat ${fn} | awk "{printf(\"  %-25s { \$\$ := ${nm}.T.%s }\n\", \$1, \$1)}" >> ${efn}
    mv_if_different ${efn} ${efn_tgt}
}

cat *.dat | sort | grep -v '^$' | uniq | awk '{printf("T_%-15s \"%s\"\n",toupper($1),$1)}' > rdl.l.2

cat rdl.l.[0-9] > rdl.l.tmp
mv_if_different rdl.l.tmp rdl.l

cat *.dat | sort | grep -v '^$' | uniq | awk '{printf("%%const T_%s\n", toupper($1))}' > rdl.t.1

cat rdl.t.[0-9] > rdl.t
mv_if_different rdl.t.tmp rdl.t

for file in *.dat; do
  base=`basename ${file} .dat`
  cat ${file} | awk '{printf("  %-23s T_%-15s\n", $1, toupper($1))}' > ${DERIV}/rdl.y.${base}
  intf=`camelize ${file}`
  make_interface ${file} ${intf}
  mk_e_fragment ${file} ${base} ${intf}
done

cc -E -P -x c -I${DERIV} rdlParseExt.ee -o rdlParseExt.e


