# Multiresolution contour plot
# Generated by plydemo

set terminal pdfcairo size 12,16 font ',10'
set output '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_9/face_contours.pdf'

set multiplot layout 4,1

set view map
set contour base
unset surface
set cntrparam levels auto 20
set xrange [-2.281540124298046e6:2.3630487951499643e6]
set yrange [-1.9120020586596192e6:1.761638123244294e6]
unset key
unset clabel
set format z ''

set title 'Level 0 (sigma=28)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_9/face_level0.dat' with lines lc 'black'

set title 'Level 1 (sigma=7.4)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_9/face_level1.dat' with lines lc 'black'

set title 'Level 2 (sigma=1.9)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_9/face_level2.dat' with lines lc 'black'

set title 'Level 3 (raw)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_9/face_level3.dat' with lines lc 'black'

unset multiplot
