# Multiresolution contour plot
# Generated by plydemo

set terminal pdfcairo size 12,16 font ',10'
set output '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_6/face_contours.pdf'

set multiplot layout 4,1

set view map
set contour base
unset surface
set cntrparam levels auto 20
set xrange [-7.986906105013423e6:7.107822966197019e6]
set yrange [-2.2776276322317384e6:2.184029607796975e6]
unset key
unset clabel
set format z ''

set title 'Level 0 (sigma=18)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_6/face_level0.dat' with lines lc 'black'

set title 'Level 1 (sigma=5.3)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_6/face_level1.dat' with lines lc 'black'

set title 'Level 2 (sigma=1.6)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_6/face_level2.dat' with lines lc 'black'

set title 'Level 3 (raw)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_3_Face_6/face_level3.dat' with lines lc 'black'

unset multiplot
