% Copyright (c) 2026 Mika Nystrom.  All rights reserved.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("plylib")
import ("meshlib")

Module ("SeedPriority")
Pqueue ("Seed", "SeedPriority")

Module ("Facet")
Module ("Segment")

library ("facetlib")
