%char [|&\^~*/%+\-?!#@<>=(){};:,.\]\[']

%const ERROR

%const T_EQ T_NEQ T_CEQ T_CNE T_WEQ T_WNE
%const T_LEQ T_GEQ T_LSHIFT T_RSHIFT T_ALSHIFT T_ARSHIFT
%const T_LAND T_LOR T_POW
%const T_PSEL T_MSEL
%const T_SCOPE T_DOTSTAR T_ARROW T_TRIGGER
%const T_PASSIGN T_MASSIGN T_TASSIGN T_DASSIGN T_RASSIGN
%const T_AASSIGN T_OASSIGN T_XASSIGN T_LSASSIGN T_RSASSIGN
%const T_ALASSIGN T_ARASSIGN
%const T_INC T_DEC
%const T_NAND T_NOR T_XNOR

%const T_MODULE T_ENDMODULE T_INPUT T_OUTPUT T_INOUT
%const T_WIRE T_REG T_LOGIC T_INTEGER T_REAL T_TIME
%const T_SIGNED T_UNSIGNED
%const T_ASSIGN
%const T_ALWAYS T_ALWAYS_COMB T_ALWAYS_FF T_ALWAYS_LATCH
%const T_POSEDGE T_NEGEDGE T_OR
%const T_IF T_ELSE T_BEGIN T_END
%const T_CASE T_CASEZ T_CASEX T_ENDCASE T_DEFAULT
%const T_UNIQUE T_PRIORITY
%const T_FOR T_WHILE T_REPEAT T_FOREVER
%const T_PARAMETER T_LOCALPARAM
%const T_GENERATE T_ENDGENERATE T_GENVAR
%const T_INITIAL T_FINAL
%const T_FUNCTION T_ENDFUNCTION T_TASK T_ENDTASK T_RETURN T_AUTOMATIC T_STATIC
%const T_PACKAGE T_ENDPACKAGE T_IMPORT T_EXPORT
%const T_TYPEDEF T_ENUM T_STRUCT T_PACKED T_UNION
%const T_INTERFACE T_ENDINTERFACE T_MODPORT
%const T_BIT T_BYTE T_SHORTINT T_INT T_LONGINT
%const T_VOID T_STRING T_CHANDLE T_TYPE T_INSIDE T_ASSERT

%token T_IDENT T_SYSIDENT T_NUMBER T_STRLIT T_DIRECTIVE T_ATTRIBUTE
