% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("cit_util")

%if defined("CM3_VERSION")
%        m3_optimize("T")
%end


c_source ("dummy")
Generic_module("Tokenizer")

library ("simpletoken")


