# Multiresolution contour plot
# Generated by plydemo

set terminal pdfcairo size 12,16 font ',10'
set output '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_2_Face_4/face_contours.pdf'

set multiplot layout 4,1

set view map
set contour base
unset surface
set cntrparam levels auto 20
set xrange [-3.4687873214147147e6:3.399625366123934e6]
set yrange [-4.244465594563002e6:3.5155527377437493e6]
unset key
unset clabel
set format z ''

set title 'Level 0 (sigma=30)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_2_Face_4/face_level0.dat' with lines lc 'black'

set title 'Level 1 (sigma=7.7)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_2_Face_4/face_level1.dat' with lines lc 'black'

set title 'Level 2 (sigma=2)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_2_Face_4/face_level2.dat' with lines lc 'black'

set title 'Level 3 (raw)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_2_Face_4/face_level3.dat' with lines lc 'black'

unset multiplot
