# Multiresolution contour plot
# Generated by plydemo

set terminal pdfcairo size 12,16 font ',10'
set output '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_4_Face_1/face_contours.pdf'

set multiplot layout 4,1

set view map
set contour base
unset surface
set cntrparam levels auto 20
set xrange [-1.1357343730912758e7:7.806752387490177e6]
set yrange [-2.26794238056438e6:1.6633702405920099e6]
unset key
unset clabel
set format z ''

set title 'Level 0 (sigma=14)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_4_Face_1/face_level0.dat' with lines lc 'black'

set title 'Level 1 (sigma=4.7)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_4_Face_1/face_level1.dat' with lines lc 'black'

set title 'Level 2 (sigma=1.5)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_4_Face_1/face_level2.dat' with lines lc 'black'

set title 'Level 3 (raw)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_4_Face_1/face_level3.dat' with lines lc 'black'

unset multiplot
