// Generated by svgates.scm

module test_alu1_gates (
  input a,
  input b,
  input op0,
  input op1,
  output y
);

  wire n5, n2, n1, n6, n4, n3;

  INV u_inv1 (.A(op1), .Y(n3));
  OR2 u_or2 (.A(op0), .B(op1), .Y(n4));
  MUX2 u_mux3 (.A(n4), .B(n3), .S(b), .Y(n2));
  AND2 u_and4 (.A(op0), .B(op1), .Y(n6));
  MUX2 u_mux5 (.A(n6), .B(n4), .S(b), .Y(n5));
  MUX2 u_mux6 (.A(n5), .B(n2), .S(a), .Y(n1));

  assign y = n1;

endmodule

// Statistics:
//   Gates: 6
//   Wires: 6
