// Generated by svgates.scm

module test_or2_gates (
  input a,
  input b,
  output y
);

  wire n1;

  OR2 u_or1 (.A(a), .B(b), .Y(n1));

  assign y = n1;

endmodule

// Statistics:
//   Gates: 1
//   Wires: 1
