// Generated by svgates.scm

module test_mixed_gates (
  input a,
  input b,
  input c,
  input d,
  output y,
  output z
);

  wire n6, n5, n4, n3, n2, n1;

  XOR2 u_xor1 (.A(c), .B(d), .Y(n3));
  OR2 u_or2 (.A(b), .B(n3), .Y(n2));
  MUX2 u_mux3 (.A(n3), .B(n2), .S(a), .Y(n1));
  TIEL u_tiel4 (.Y(n5));
  MUX2 u_mux5 (.A(c), .B(n5), .S(b), .Y(n6));
  MUX2 u_mux6 (.A(n6), .B(n5), .S(a), .Y(n4));

  assign y = n1;
  assign z = n4;

endmodule

// Statistics:
//   Gates: 6
//   Wires: 6
