// Generated by svgates.scm

module test_majority_gates (
  input a,
  input b,
  input c,
  output y
);

  wire n3, n2, n1;

  OR2 u_or1 (.A(b), .B(c), .Y(n2));
  AND2 u_and2 (.A(b), .B(c), .Y(n3));
  MUX2 u_mux3 (.A(n3), .B(n2), .S(a), .Y(n1));

  assign y = n1;

endmodule

// Statistics:
//   Gates: 3
//   Wires: 3
