// Generated by svgates.scm

module test_and2_gates (
  input a,
  input b,
  output y
);

  wire n1;

  AND2 u_and1 (.A(a), .B(b), .Y(n1));

  assign y = n1;

endmodule

// Statistics:
//   Gates: 1
//   Wires: 1
