// Generated by svgates.scm

module test_mux4_gates (
  input s0,
  input s1,
  input d0,
  input d1,
  input d2,
  input d3,
  output y
);

  wire n3, n2, n1;

  MUX2 u_mux1 (.A(d1), .B(d3), .S(s1), .Y(n2));
  MUX2 u_mux2 (.A(d0), .B(d2), .S(s1), .Y(n3));
  MUX2 u_mux3 (.A(n3), .B(n2), .S(s0), .Y(n1));

  assign y = n1;

endmodule

// Statistics:
//   Gates: 3
//   Wires: 3
