// Generated by svgates.scm

module test_decoder_gates (
  input a,
  input b,
  output y0,
  output y1,
  output y2,
  output y3
);

  wire n6, n5, n4, n3, n2, n1;

  NOR2 u_nor1 (.A(a), .B(b), .Y(n1));
  TIEL u_tiel2 (.Y(n3));
  MUX2 u_mux3 (.A(b), .B(n3), .S(a), .Y(n2));
  INV u_inv4 (.A(b), .Y(n5));
  AND2 u_and5 (.A(a), .B(n5), .Y(n4));
  AND2 u_and6 (.A(a), .B(b), .Y(n6));

  assign y0 = n1;
  assign y1 = n2;
  assign y2 = n4;
  assign y3 = n6;

endmodule

// Statistics:
//   Gates: 6
//   Wires: 6
