// Generated by svgates.scm

module test_xor_chain_gates (
  input a,
  input b,
  input c,
  input d,
  output y
);

  wire n5, n2, n1, n3, n4;

  XOR2 u_xor1 (.A(c), .B(d), .Y(n3));
  XNOR2 u_xnor2 (.A(c), .B(d), .Y(n4));
  MUX2 u_mux3 (.A(n4), .B(n3), .S(b), .Y(n2));
  MUX2 u_mux4 (.A(n3), .B(n4), .S(b), .Y(n5));
  MUX2 u_mux5 (.A(n5), .B(n2), .S(a), .Y(n1));

  assign y = n1;

endmodule

// Statistics:
//   Gates: 5
//   Wires: 5
