// Generated by svgates.scm

module test_priority_gates (
  input a,
  input b,
  input c,
  input d,
  output y1,
  output y0
);

  wire n3, n2, n4, n1;

  OR2 u_or1 (.A(c), .B(d), .Y(n1));
  TIEH u_tieh2 (.Y(n4));
  MUX2 u_mux3 (.A(n4), .B(d), .S(c), .Y(n3));
  MUX2 u_mux4 (.A(d), .B(n3), .S(b), .Y(n2));

  assign y1 = n1;
  assign y0 = n2;

endmodule

// Statistics:
//   Gates: 4
//   Wires: 4
