// Generated by svgates.scm

module test_adder_gates (
  input a,
  input b,
  input cin,
  output sum,
  output cout
);

  wire n6, n5, n4, n3, n2, n1;

  XNOR2 u_xnor1 (.A(b), .B(cin), .Y(n2));
  XOR2 u_xor2 (.A(b), .B(cin), .Y(n3));
  MUX2 u_mux3 (.A(n3), .B(n2), .S(a), .Y(n1));
  OR2 u_or4 (.A(b), .B(cin), .Y(n5));
  AND2 u_and5 (.A(b), .B(cin), .Y(n6));
  MUX2 u_mux6 (.A(n6), .B(n5), .S(a), .Y(n4));

  assign sum = n1;
  assign cout = n4;

endmodule

// Statistics:
//   Gates: 6
//   Wires: 6
