// Generated by svgates.scm

module test_parity8_gates (
  input a,
  input b,
  input c,
  input d,
  input e,
  input f,
  input g,
  input h,
  output p
);

  wire n13, n2, n1, n3, n12, n4, n11, n5, n10, n6, n9, n7, n8;

  XOR2 u_xor1 (.A(g), .B(h), .Y(n7));
  XNOR2 u_xnor2 (.A(g), .B(h), .Y(n8));
  MUX2 u_mux3 (.A(n8), .B(n7), .S(f), .Y(n6));
  MUX2 u_mux4 (.A(n7), .B(n8), .S(f), .Y(n9));
  MUX2 u_mux5 (.A(n9), .B(n6), .S(e), .Y(n5));
  MUX2 u_mux6 (.A(n6), .B(n9), .S(e), .Y(n10));
  MUX2 u_mux7 (.A(n10), .B(n5), .S(d), .Y(n4));
  MUX2 u_mux8 (.A(n5), .B(n10), .S(d), .Y(n11));
  MUX2 u_mux9 (.A(n11), .B(n4), .S(c), .Y(n3));
  MUX2 u_mux10 (.A(n4), .B(n11), .S(c), .Y(n12));
  MUX2 u_mux11 (.A(n12), .B(n3), .S(b), .Y(n2));
  MUX2 u_mux12 (.A(n3), .B(n12), .S(b), .Y(n13));
  MUX2 u_mux13 (.A(n13), .B(n2), .S(a), .Y(n1));

  assign p = n1;

endmodule

// Statistics:
//   Gates: 13
//   Wires: 13
