// Generated by svgates.scm

module test_compare_gates (
  input a,
  input b,
  output eq,
  output gt,
  output lt
);

  wire n5, n4, n3, n2, n1;

  XNOR2 u_xnor1 (.A(a), .B(b), .Y(n1));
  INV u_inv2 (.A(b), .Y(n3));
  AND2 u_and3 (.A(a), .B(n3), .Y(n2));
  TIEL u_tiel4 (.Y(n5));
  MUX2 u_mux5 (.A(b), .B(n5), .S(a), .Y(n4));

  assign eq = n1;
  assign gt = n2;
  assign lt = n4;

endmodule

// Statistics:
//   Gates: 5
//   Wires: 5
