# Multiresolution contour plot
# Generated by plydemo

set terminal pdfcairo size 12,16 font ',10'
set output '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_4_Face_2/face_contours.pdf'

set multiplot layout 4,1

set view map
set contour base
unset surface
set cntrparam levels auto 20
set xrange [-1.717328619502265e7:1.1336492594753448e7]
set yrange [-1.4761535703036e6:1.1752688349471001e6]
unset key
unset clabel
set format z ''

set title 'Level 0 (sigma=9.8)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_4_Face_2/face_level0.dat' with lines lc 'black'

set title 'Level 1 (sigma=3.6)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_4_Face_2/face_level1.dat' with lines lc 'black'

set title 'Level 2 (sigma=1.3)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_4_Face_2/face_level2.dat' with lines lc 'black'

set title 'Level 3 (raw)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_4_Face_2/face_level3.dat' with lines lc 'black'

unset multiplot
