% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("cit_util")


_exec(["../generator/" & TARGET & "/generator","../src/common.scm","../src/stdf.scm","exit"])

include ("../" & TARGET & "/derived.m3m")

Module ("StdfI1")
Module ("StdfI2")
Module ("StdfI4")
Module ("StdfU1")
Module ("StdfU2")
Module ("StdfU4")
Module ("StdfR4")
Module ("StdfN1")
Module ("StdfB1")
Module ("StdfBn")
Module ("StdfC1")
Module ("StdfCn")
Module ("StdfDn")
Module ("StdfVn")

Module ("StdfRd")

Interface ("StdfE")
Module ("StdfParser")
Interface ("StdfRecordObject")
Interface ("StdfRecordObjectClass")
Sequence ("StdfRecordObject", "StdfRecordObject")

Table("StdfCardPairRec", "CardPair", "StdfRecordTypes")

Module ("StdfParseTable")

module ("StdfConstProc")

module ("StdfWr")

module ("StdfRand")

library ("stdf")
