#!/usr/bin/env python3
"""
Extract 99 CES (Colour Evaluation Samples) reflectance spectra and
CIE 1964 10-degree observer CMFs from colour-science, formatted as
Scheme data for photopic TM-30 implementation.

Usage:
    python3 extract-ces.py > ces99.scm

Requires: colour-science (pip install colour-science)
Data source: CIE 224:2017 via colour-science BSD-3 licensed dataset.
"""

import sys
import numpy as np
from colour.quality.cfi2017 import load_TCS_CIE2017
from colour.colorimetry import SpectralShape, MSDS_CMFS

# Match photopic grid: 380-770nm at 1nm = 391 points
GRID_LO = 380
GRID_HI = 770
GRID_N = 391

# --- CES data ---
# CIE 2017 standard uses 380-780nm; load at that range, then trim to 770nm
shape_full = SpectralShape(380, 780, 1)
sds = load_TCS_CIE2017(shape_full)

assert sds.values.shape[0] >= GRID_N, \
    f"Expected >= {GRID_N} rows, got {sds.values.shape[0]}"
assert sds.values.shape[1] == 99, \
    f"Expected 99 columns, got {sds.values.shape[1]}"
ces_values = sds.values[:GRID_N, :]

# --- 10-degree observer CMFs ---
cmfs_10 = MSDS_CMFS["CIE 1964 10 Degree Standard Observer"]
# Align to our grid shape
cmfs_shape = SpectralShape(GRID_LO, GRID_HI, 1)
cmfs_aligned = cmfs_10.copy().align(cmfs_shape)
cmf_values = cmfs_aligned.values[:GRID_N, :]
assert cmf_values.shape == (GRID_N, 3), \
    f"Expected ({GRID_N}, 3), got {cmf_values.shape}"

out = sys.stdout

out.write(";; CIE 224:2017 Colour Evaluation Samples (99 CES)\n")
out.write(";; and CIE 1964 10-degree observer colour matching functions\n")
out.write(";; Reflectance/CMF data at 1nm resolution, 380-770nm (391 points)\n")
out.write(";; Auto-generated by extract-ces.py from colour-science dataset\n")
out.write(";; SPDX-License-Identifier: BSD-3-Clause (colour-science data)\n\n")

out.write(f"(define *ces-count* {99})\n\n")

# Write CES reflectance data
out.write("(define *ces-reflectance*\n")
out.write(f"  (vector ;; {99} CES, each {GRID_N} values\n")

for j in range(99):
    vals = ces_values[:, j]
    out.write(f"    ;; CES {j+1}\n")
    out.write("    (vector")
    for i, v in enumerate(vals):
        if i % 10 == 0:
            out.write("\n      ")
        out.write(f" {v:.6f}")
    out.write(")\n")

out.write("  ))\n\n")

# Write 10-degree CMFs
def write_cmf_vector(name, col, comment):
    out.write(f";; {comment}\n")
    out.write(f"(define {name}\n")
    out.write("  (vector")
    vals = cmf_values[:, col]
    for i, v in enumerate(vals):
        if i % 8 == 0:
            out.write("\n    ")
        out.write(f" {v:.8f}")
    out.write("))\n\n")

write_cmf_vector("*cmf10-x*", 0, "CIE 1964 10-degree x-bar")
write_cmf_vector("*cmf10-y*", 1, "CIE 1964 10-degree y-bar")
write_cmf_vector("*cmf10-z*", 2, "CIE 1964 10-degree z-bar")
