# Multiresolution contour plot
# Generated by plydemo

set terminal pdfcairo size 12,16 font ',10'
set output '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_1_Face_5/face_contours.pdf'

set multiplot layout 4,1

set view map
set contour base
unset surface
set cntrparam levels auto 20
set xrange [-2.0178899713962986e6:1.6630385280098803e6]
set yrange [-1.5411274805294832e6:2.3226118119196156e6]
unset key
unset clabel
set format z ''

set title 'Level 0 (sigma=31)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_1_Face_5/face_level0.dat' with lines lc 'black'

set title 'Level 1 (sigma=7.9)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_1_Face_5/face_level1.dat' with lines lc 'black'

set title 'Level 2 (sigma=2)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_1_Face_5/face_level2.dat' with lines lc 'black'

set title 'Level 3 (raw)'
splot '/Users/mika/al-ga-work/async-toolkit/m3utils/m3utils/Al_Ga/contour_out/all/550_1_1_Face_5/face_level3.dat' with lines lc 'black'

unset multiplot
