% Copyright (c) 2026 Mika Nystrom.  All rights reserved.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("plylib")
import ("meshlib")
import ("facetlib")
import ("curvlib")

implementation ("Main")

program ("plydemo")
