%char [|&\^~*/%+\-?!#@<>=(){};:,.\]\[]

%const ERROR
%const T_EQ T_NEQ T_LEQ T_GEQ T_ARROW T_DOTDOT T_COLON2 T_EXP
%const T_LSHIFT T_RSHIFT T_PIPE2 T_AMP2
%const T_PASSIGN T_MASSIGN T_TASSIGN T_DASSIGN T_RASSIGN
%const T_AASSIGN T_OASSIGN T_XASSIGN T_LSASSIGN T_RSASSIGN
%const T_INC T_DEC
%const T_BOX T_LOOP
%const T_PLOOP T_MLOOP T_ALOOP T_OLOOP T_XLOOP
%const T_SLOOP T_BLOOP T_CLOOP T_BOXLOOP T_CLLOOP
%const T_FUNCTION T_STRUCTURE T_INT T_SINT T_BOOL T_BOOLEAN
%const T_CONST T_TRUE T_FALSE T_SKIP T_ERROR T_ELSE T_STRING
%const T_DIRECTIVES
%token T_IDENT T_INTEGER T_STRING_LIT
